"""empty message

Revision ID: 1b28c3cf615d
Revises: fdc53079cbc1
Create Date: 2019-07-12 18:18:24.559423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b28c3cf615d'
down_revision = 'fdc53079cbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('LAN_IP', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'LAN_IP')
    # ### end Alembic commands ###
