"""empty message

Revision ID: 295d27ddcbff
Revises: 1b28c3cf615d
Create Date: 2019-07-12 18:47:56.292691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295d27ddcbff'
down_revision = '1b28c3cf615d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('ssh_port', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'ssh_port')
    # ### end Alembic commands ###
