"""empty message

Revision ID: 2c0de1382bc1
Revises: cfe95044dc24
Create Date: 2019-07-15 16:05:23.365441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0de1382bc1'
down_revision = 'cfe95044dc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('register_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'register_date')
    # ### end Alembic commands ###
