"""empty message

Revision ID: 37684631486b
Revises: 5a0d48e81dd0
Create Date: 2019-07-11 16:55:52.469360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37684631486b'
down_revision = '5a0d48e81dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('os_password', sa.String(length=64), nullable=True))
    op.add_column('client', sa.Column('os_username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'os_username')
    op.drop_column('client', 'os_password')
    # ### end Alembic commands ###
