"""empty message

Revision ID: 38422c4643f7
Revises: 1de3eb20ccf1
Create Date: 2019-07-15 14:38:34.975076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38422c4643f7'
down_revision = '1de3eb20ccf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('register_date', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'register_date')
    # ### end Alembic commands ###
