"""empty message

Revision ID: 6f00b02b7cf3
Revises: 
Create Date: 2019-07-15 16:11:54.054673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f00b02b7cf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('os_username', sa.String(length=64), nullable=True),
    sa.Column('os_password', sa.String(length=64), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('public_IP', sa.String(length=32), nullable=True),
    sa.Column('LAN_IP', sa.String(length=32), nullable=True),
    sa.Column('os', sa.String(length=32), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('platform_version', sa.String(length=64), nullable=True),
    sa.Column('register', sa.Integer(), nullable=True),
    sa.Column('register_date', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
