"""empty message

Revision ID: b92c39579876
Revises: 37684631486b
Create Date: 2019-07-12 17:56:20.862249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b92c39579876'
down_revision = '37684631486b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'LAN_IP')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('LAN_IP', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
