"""empty message

Revision ID: cfe95044dc24
Revises: e51ebae19319
Create Date: 2019-07-15 16:05:09.215446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfe95044dc24'
down_revision = 'e51ebae19319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'register_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('register_date', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
