"""empty message

Revision ID: e51ebae19319
Revises: f7075b2c34ce
Create Date: 2019-07-15 16:02:19.340877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51ebae19319'
down_revision = 'f7075b2c34ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('register_date', sa.Float(precision=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'register_date')
    # ### end Alembic commands ###
