"""empty message

Revision ID: f7075b2c34ce
Revises: 38422c4643f7
Create Date: 2019-07-15 16:01:51.324411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7075b2c34ce'
down_revision = '38422c4643f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'register_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('register_date', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
